name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt update && sudo apt install -y git make
          make setup
          git submodule update --init --recursive
      
      - name: Check containerd
        run: |
          containerd --version